version: "3.7"
services:

  jupyter-lab:
    hostname: jupyter-lab
    build:
      dockerfile: ./jupyter-lab/Dockerfile
      context: .
    restart: always
    volumes:
      - "../notebooks/:/home/jovyan/notebooks"
    security_opt:
      - label=disable
    ports:
      - "8888:8888"

  db-server:
    hostname: db-server
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:8.0
    restart: always
    security_opt:
      - label=disable
    environment:
      MYSQL_ROOT_PASSWORD: student
      MYSQL_USER: student
      MYSQL_PASSWORD: student
      MYSQL_DATABASE: 4iz562
    volumes:
      - "../mysql-data:/var/lib/mysql/"
    ports:
      - "3306:3306"

volumes:
  mysql-data:

networks:
  holopage: