version: "3.7"
services:
 
  jupyter-lab:
    domainname: holopage.com
    hostname: jupyter-lab
    container_name: jupyter-lab.holopage.com
    networks:
      - holopage
    dns: 192.168.1.1
    build:
      dockerfile: ./jupyter-lab/Dockerfile
      context: .
    restart: always
    security_opt:
      - label=disable
    ports:
      - "8888:8888"
networks:
  holopage:
